name: Deploy to GitHub Pages
on:
push:
branches: [ "main" ]
jobs:
build-deploy:
runs-on: ubuntu-latest
permissions:
pages: write
id-token: write
steps:
- uses: actions/checkout@v4
with:
submodules: false
-name: Setup Pages
uses: actions/configure-pages@v3
-name: Upload artifact
uses: actions/upload-pages-artifact@v2
with:
path: ./
-name: Deploy
uses: actions/deploy-pages@v2
